export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/go/bin:$PATH"
export PATH="${BREW_PREFIX}/bin:$PATH"
export PATH="${BREW_PREFIX}/sbin:$PATH"
export PATH="${BREW_PREFIX}/opt/openssl/bin:$PATH" # Make proper openssl the default openssl
export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="$PATH:$HOME/.gem/bin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:${BREW_PREFIX}/gnu-sed/libexec/gnubin" # GNU sed
export PATH="$PATH:${BREW_PREFIX}/make/bin" # GNU make
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
